nelmio_api_doc:
    areas: # Définir les zones où la documentation est disponible
        default:
            path_patterns: # Correspond aux chemins de vos API
                - ^/api
    documentation:
        info:
            title: "API Documentation"
            description: "Documentation de l'API pour votre projet."
            version: "1.0.0"
